backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Data"
    name: "data"
    files:
      - label: "Users"
        name: "users"
        file: "public/data/users.json"
        fields:
          - label: Users
            name: users
            widget: list
            fields:
              - {label: First name, name: firstname, widget: string}
              - {label: Last name, name: lastname, widget: string}
              - {label: Position, name: position, widget: string}